"""added Post

Revision ID: 91e5ea9ab78a
Revises: 3801971ffc50
Create Date: 2024-12-04 11:58:30.559229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e5ea9ab78a'
down_revision = '3801971ffc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('band_ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band', sa.Integer(), nullable=False),
    sa.Column('lookingfor', sa.String(length=50), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['band'], ['band.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('band_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_members',
    sa.Column('band_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('instrument', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('band_id', 'user_id')
    )
    op.drop_table('band_ad')
    op.drop_table('text_post')
    op.drop_table('image_post')
    # ### end Alembic commands ###
