"""add_unique_constraint_to_interest

Revision ID: a70731a19bf6
Revises: 023af0db9de0
Create Date: 2025-06-11 21:13:28.335287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70731a19bf6'
down_revision = '023af0db9de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_ad_uc', ['user_id', 'ad_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.drop_constraint('_user_ad_uc', type_='unique')

    # ### end Alembic commands ###
