"""Add interest model

Revision ID: e150a6abcf88
Revises: d988d1322ef3
Create Date: 2024-12-09 11:42:01.052612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e150a6abcf88'
down_revision = 'd988d1322ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band', sa.Integer(), nullable=False),
    sa.Column('lookingfor', sa.String(length=50), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['band'], ['band.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['bandad.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('band_ad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_ad',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('band', sa.INTEGER(), nullable=False),
    sa.Column('lookingfor', sa.VARCHAR(length=50), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['band'], ['band.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('interest')
    op.drop_table('bandad')
    # ### end Alembic commands ###
