"""made Band and BandMember tables

Revision ID: f7770a18c2ee
Revises: 131c5fb61fe6
Create Date: 2024-12-03 14:44:06.565606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7770a18c2ee'
down_revision = '131c5fb61fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_member',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('band_id', 'user_id')
    )
    op.drop_table('band_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_members',
    sa.Column('band_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('instrument', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('band_id', 'user_id')
    )
    op.drop_table('band_member')
    # ### end Alembic commands ###
